name: Pull Request CI Check
on: [pull_request]
jobs:

  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:

    - name: Check out the code
      uses: actions/checkout@v2

    - name: Make ci
      run: make ci
